### PR TITLE
Fixed grand challenge algorithm integration, simplified algorithm template

### LINKED ISSUE #275: Fixing grand-challenge integration with algorithm/processor template
### Description

The current algorithm/processor template does not work with grand-challenge, because it expects different inputs. 

It now seems broken because:
1) internally MHD files are replaced by MHA files in grand-challenge, and in evalutils MHD files are expected.  This can be easily fixed by including 
2) CSV files cannot be served on grand-challenge, because these are not images. This can not be easily solved, so, for now, we'll just make it the example template a candidate detector based on images.

### What I Did

* created the processor/algorithm template with --dev flag (necessary for testing)
* ran ./build.sh 
* ran ./export.sh
* uploaded the resulting file to grand-challenge algorithm
* gave it the test data files (2x*.mhd, 2x*.zraw, 1x*.csv)

For uploaded .mhd/.zraw files:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/processor/process.py", line 86, in <module>
    Ddhdemo().process()
  File "/home/processor/.local/lib/python3.7/site-packages/evalutils/evalutils.py", line 138, in process
    self.load()
  File "/home/processor/.local/lib/python3.7/site-packages/evalutils/evalutils.py", line 83, in load
    folder=self._input_path, file_loader=file_loader, filter=filter
  File "/home/processor/.local/lib/python3.7/site-packages/evalutils/evalutils.py", line 115, in _load_cases
    f"Could not load any files in {folder} with " f"{file_loader}."
evalutils.exceptions.FileLoaderError: Could not load any files in /input with <evalutils.io.SimpleITKLoader object at 0x7f8f959fa9d0>.
```

For uploaded .csv files:
```
The following image files could not be processed in reader study None:

candidates.csv

The following file formats are supported: .mhd, .mha, .tiff
```

### PR DESCRIPTION
**Pull request by silvandeleemput**
Closes #275

* Removed candidates.csv (now computes candidates based on input image)
* Changed example algorithm template (image -> candidate detection)
* Changed algorithm test

### CODE REVIEW

**Comment by silvandeleemput** [comment]
This PR also makes the algorithm-template functional with grand-challenge/algorithms at 11-2-2020.

**Comment by jmsmkn** [comment]
Any idea about the broken test? Seeing that one on another branch too

**Comment by jmsmkn** [comment]
Ah `Killed` 

The templated algorithm uses too much memory and is killed by docker.

**Comment by silvandeleemput** [comment]
@jmsmkn Ah yes, I just reached the same conclusion.

**Comment by silvandeleemput** [comment]
The issue was indeed related to the .gitattributes -> .gitattributes.j2 refactor. I have removed it from this PR.

**Pull request merged**
