### PR TITLE
Added use_memory_efficient_edt switch to stats methods

### LINKED ISSUE #303: Create a switch to toggle between memory lean `distance_transform_edt_float32` and original `distance_transform_edt` version
### Description

The following methods all use the (more memory efficient but slower) `distance_transform_edt_float32` and it would be nice to add a toggle to use the original `distance_transform_edt`. 

* hausdorff_distance_measures
* __surface_distances
* __directed_contour_distances

### PR DESCRIPTION
**Pull request by silvandeleemput**
Closes #303

### This PR 

* Adds a `use_memory_efficient_edt` switch to all methods computing edt transforms in stats.py.
* The default for the flag is set to the (non-memory-efficient) `scipy.ndimage.morphology.distance_transform_edt` version.
* When enabled it uses the `distance_transform_edt_float32` version in stats.py.
* Docstring has been added for the new parameter as well

@jmsmkn The current default was the memory-efficient version, but now it will use the (non-memory-efficient) `scipy.ndimage.morphology.distance_transform_edt` version. I figured that it would be more desirable to move away from custom methods. Is it ok to break it in this way, or would we rather put the default to the memory-efficient version we used before?

### CODE REVIEW

**Comment by jmsmkn** [comment]
Default should be to use the memory efficient version.

**Comment by silvandeleemput** [comment]
This PR should be merged or rebased to master after https://github.com/comic/evalutils/pull/313 lands.

**Comment by jmsmkn** [comment]
Looking at the constructions, wouldn't it be nicer to pass `edt_method` around rather than have a boolean option and then a few switches everywhere, then default that to the one included in this library.

**Comment by silvandeleemput** [comment]
That would be both cleaner and more flexible, but as an interface for the user, I think you only would ever want to change between those two methods, hence a boolean should be simpler and sufficient.

However, if you think that directly supplying the edt_method is better, I would be happy to change it.

**Comment by jmsmkn** [comment]
No strong opinions about it, in general I think it's a better pattern and was just thinking to get it right now as public interfaces should never change.

**Review by jmsmkn — APPROVED** [review]
Will leave the API change up to you but this is also good.

**Review by jmsmkn — APPROVED** [review]

**Pull request merged**
